### ISSUE TITLE
Harvester stops reading quiet files prematurely (Harvester timeout?)

### ISSUE THREAD

**Issue by NickMontgomery** [elasticsearch/logstash-forwarder#107]
I have a series of log files that occasionally get large amounts of entries but can sit quiet for a long period of time. However, after a certain period of time, the lumberjack harvester stops watching files because they haven't been modified. 

Is it possible to set a global or file-by-file timeout time for the harvester? Is there something I am missing?

Thanks!

**Comment by jordansissel** [comment]
The 'dead time' on files causes it to ignore old files or close idle ones. This behavior was a bit wonky at first, but I think it works correctly now.

Please reopen if you feel this isn't know :)
