### ISSUE TITLE
Offset behavior question

### ISSUE THREAD

**Issue by bitsofinfo** [elasticsearch/logstash-forwarder#122]
What is the behavior w/ regards to when the "offset" gets moved forward? Is that only moved forward *after* a successful transmission of the event and ACK from the receiver?

**Comment by jordansissel** [comment]
I'm not sure what you mean by 'offset gets moved forward'.

The order is:
* harvester reads data, sends to spooler
* spooler collects logs until buffer is full or time expires (seconds)
* publisher ships a spool over the network
* publisher waits for that spool to be acknowledged
* registrar is notified that the spool was acknowledged 
* registrar writes a new state about the last known offsets of acknowlegdged events.

**Comment by jordansissel** [comment]
Hopefully this clarifies things :)
