### ISSUE TITLE
need multiline support asap, willing to do the work, would love some pointers

### ISSUE THREAD

**Issue by tedcaoboston** [elasticsearch/logstash-forwarder#128]
Hi Jordan,
for a project I need multiline support to ship java stack traces asap (and found logstash agent to be too heavy weight), I am willing to do the work and hope you could give me some pointers on where/how best to make the changes (little bit of general structural pointers greatly appreciated).

Thanks a lot!

- Ted

**Comment by jordansissel** [comment]
At this time, multiline should still be done in Logstash (with the multiline filter or the multiline codec). 

We're freezing features on lsf for now until [this experiment](http://www.elasticsearch.org/guide/en/logstash/roadmap/current/index.html#_logstash_forwarder) is executed to see if we can replace LSF with something better and more fulfilling of user needs.
