### ISSUE TITLE
events with same exact timestamps not logged

### ISSUE THREAD

**Issue by Radek007** [elasticsearch/logstash-forwarder#148]
I have a cisco device that sends syslog messages. Some messages have same exact timestamps. Only sequence numbers are different. For example:

1246235: Jan 31 08:31:48.286: %DOT1X (...)
1246236: Jan 31 08:31:48.286: %AUTHMGR (...)

Only the first event is logged in logstash (sequence number 1246235). Second event is never logged.

**Comment by jordansissel** [comment]
Can you reopen this bug under logstash? This project is logstash-forwarder. It doesn't receive syslog messages.
