### ISSUE TITLE
duplicate logs?

### ISSUE THREAD

**Issue by sysmonk** [elasticsearch/logstash-forwarder#149]
While searching for some logs, i noticed that there are duplicate logs in ElasticSearch.
Logs are exactly the same (same server,file,timestamp,message and etc), except for the 'offset' being different by 2 (i.e. one log has offset 100 other has offset 102).Logstash-forwarder was not restarted for at least half a dayafter the current logfile was rotated.

I've got another case where there's even 3 copies of the log, but they have same offset and logstash-forwarder was restarted a few times before the log got rotated.

**Comment by jordansissel** [comment]
I think this is fixed in master which uses `ReadBytes("\n")` instead of ReadLine
