### ISSUE TITLE
Dealing with log duplicates in cloud servers?

### ISSUE THREAD

**Issue by teu** [elasticsearch/logstash-forwarder#158]
Hi,

just want to pick your minds for a problematic issue.
We use AWS servers that spawn whenever we need them, sometimes whey spawn with log files already there. 
The problem is, when I spawn an instance that has 10MB of logs, logstash-forwarder forwards all of them, even though they would have been sent a long time ago.

What would you guys suggest to minimise sending duplicate logs like that?

Thanks

**Comment by jordansissel** [comment]
You can probalby use the `-tail` flag for this which makes it start at the end of files.
