### ISSUE TITLE
Daemon overwrites its own state file when watching multiple types of logs.

### ISSUE THREAD

**Issue by eshelman** [elasticsearch/logstash-forwarder#167]
To reproduce, create a configuration file which watches two different types of logs (e.g. apache_access and syslog):

````
{
  "network": {
    "servers": [ "10.0.0.1:5043" ],
    "ssl certificate": "/etc/pki/tls/certs/logstash-forwarder.crt",
    "ssl key": "/etc/pki/tls/private/logstash-forwarder.key",
    "ssl ca": "/etc/pki/tls/certs/logstash-forwarder.crt"
  },
  "files": [
    {
      "paths": [ "/var/log/httpd/access_log" ],
      "fields": { "type": "apache-access" }
    }, {
      "paths": [ "/var/log/messages" ],
      "fields": { "type": "syslog" }
    }
  ]
}
````

You'll see the .logstash-forwarder file get updated with one type of logs. For example, after reading apache it might read:
````
{"/var/log/httpd/access_log":{"source":"/var/log/httpd/access_log","offset":4095918,"inode":131475,"device":2311}}
````

Now manually force an update to syslog by inserting a test event:
````
logger Test event
````

Suddenly, the .logstash-forwarder file contains only the state information for /var/log/messages:
````
{"/var/log/messages":{"source":"/var/log/messages","offset":4888307,"inode":132308,"device":2311}}
````

Do I correctly presume that this is why people are often complaining about logstash-forwarder often re-reading some of their logs from the beginning?

**Comment by jordansissel** [comment]
I'm pretty sure this is fixed in master.
