### ISSUE TITLE
Logs duplicating every night, logstash forwarder + logrotate

### ISSUE THREAD

**Issue by marianogg9** [elasticsearch/logstash-forwarder#176]
Hi @jordansissel. I don't know if this has been mentioned before, but I'm seeing varnishncsa logs get duplicated every night. Today I've installed the new logstash-forwarded and will check on this tomorrow, but last night this issue presented again with lumberjack 0.1.2. I don't see why could this be happening, here's my logrotate.d/varnish file: https://gist.github.com/marianogg9/9469807
Here's my varnishncsa.json config file: https://gist.github.com/marianogg9/9469837
Any comments will be appreciated.
Thanks!

**Comment by ernetas** [comment]
Seems to be fixed in the latest logstash-forwarder release in the apt-get repos.

**Comment by jordansissel** [comment]
Closing, I think this is fixed.
