### ISSUE TITLE
portability issues on HP-UX

### ISSUE THREAD

**Issue by Nagilum23** [elasticsearch/logstash-forwarder#20]
Compiling with gcc 4.6.3 on HP-UX 11.23:
lumberjack $ gmake
Makefile:33: warning: overriding recipe for target `clean'
Makefile.ext:15: warning: ignoring old recipe for target `clean'
gcc -D_POSIX_C_SOURCE=199309 -std=c99 -Wall -Wextra -Werror -pipe -g -Wno-unused-function -Ibuild/include    -c -o lumberjack.o lumberjack.c
In file included from /usr/local/include/openssl/ssl.h:1361:0,
                 from proto.h:7,
                 from lumberjack.c:16:
/usr/local/include/openssl/dtls1.h:236:17: error: field 'next_timeout' has incomplete type
lumberjack.c:37:13: error: 'no_argument' undeclared here (not in a function)
lumberjack.c:46:14: error: 'required_argument' undeclared here (not in a function)
lumberjack.c: In function 'set_resource_limits':
lumberjack.c:80:17: error: storage size of 'limits' isn't known
lumberjack.c:83:3: error: implicit declaration of function 'nice' [-Werror=implicit-function-declaration]
lumberjack.c:84:3: error: implicit declaration of function '__STRING' [-Werror=implicit-function-declaration]
lumberjack.c:84:3: error: format '%s' expects argument of type 'char *', but argument 6 has type 'int' [-Werror=format]
lumberjack.c:101:9: error: request for member 'rlim_cur' in something not a structure or union
lumberjack.c:101:27: error: request for member 'rlim_max' in something not a structure or union
lumberjack.c:101:3: error: statement with no effect [-Werror=unused-value]
lumberjack.c:103:28: error: request for member 'rlim_max' in something not a structure or union
lumberjack.c:103:10: error: format '%ld' expects argument of type 'long int', but argument 3 has type 'struct option_doc *' [-Werror=format]
lumberjack.c:104:3: error: implicit declaration of function 'setrlimit' [-Werror=implicit-function-declaration]
lumberjack.c:104:18: error: 'RLIMIT_NOFILE' undeclared (first use in this function)
lumberjack.c:104:18: note: each undeclared identifier is reported only once for each function it appears in
lumberjack.c:105:3: error: format '%s' expects argument of type 'char *', but argument 6 has type 'int' [-Werror=format]
lumberjack.c:105:3: error: request for member 'rlim_max' in something not a structure or union
lumberjack.c:120:9: error: request for member 'rlim_cur' in something not a structure or union
lumberjack.c:120:27: error: request for member 'rlim_max' in something not a structure or union
lumberjack.c:120:3: error: statement with no effect [-Werror=unused-value]
lumberjack.c:123:18: error: 'RLIMIT_RSS' undeclared (first use in this function)
lumberjack.c:124:3: error: format '%s' expects argument of type 'char *', but argument 6 has type 'int' [-Werror=format]
lumberjack.c:124:3: error: request for member 'rlim_max' in something not a structure or union
lumberjack.c:80:17: error: unused variable 'limits' [-Werror=unused-variable]
lumberjack.c: In function 'main':
lumberjack.c:143:61: error: invalid application of 'sizeof' to incomplete type 'struct option' 
lumberjack.c:143:52: error: invalid operands to binary * (have 'int' and 'struct option_doc *')
lumberjack.c:143:68: error: passing argument 2 of 'realloc' makes integer from pointer without a cast [-Werror]
/usr/local/include/jemalloc/jemalloc.h:50:23: note: expected 'size_t' but argument is of type 'struct option_doc *'
lumberjack.c:144:5: error: invalid use of undefined type 'struct option'
lumberjack.c:144:19: error: dereferencing pointer to incomplete type
lumberjack.c:144:22: error: request for member 'name' in something not a structure or union
lumberjack.c:144:5: error: statement with no effect [-Werror=unused-value]
lumberjack.c:145:5: error: invalid use of undefined type 'struct option'
lumberjack.c:145:19: error: dereferencing pointer to incomplete type
lumberjack.c:145:22: error: request for member 'has_arg' in something not a structure or union
lumberjack.c:145:5: error: statement with no effect [-Werror=unused-value]
lumberjack.c:146:5: error: invalid use of undefined type 'struct option'
lumberjack.c:147:19: error: dereferencing pointer to incomplete type
lumberjack.c:147:22: error: request for member 'val' in something not a structure or union
lumberjack.c:147:5: error: statement with no effect [-Werror=unused-value]
lumberjack.c:151:59: error: invalid application of 'sizeof' to incomplete type 'struct option' 
lumberjack.c:151:50: error: invalid operands to binary * (have 'int' and 'struct option_doc *')
lumberjack.c:151:66: error: passing argument 2 of 'realloc' makes integer from pointer without a cast [-Werror]
/usr/local/include/jemalloc/jemalloc.h:50:23: note: expected 'size_t' but argument is of type 'struct option_doc *'
lumberjack.c:152:3: error: invalid use of undefined type 'struct option'
lumberjack.c:152:17: error: dereferencing pointer to incomplete type
lumberjack.c:152:20: error: request for member 'name' in something not a structure or union
lumberjack.c:152:3: error: statement with no effect [-Werror=unused-value]
lumberjack.c:155:3: error: implicit declaration of function 'getopt_long_only' [-Werror=implicit-function-declaration]
lumberjack.c:159:9: error: implicit declaration of function 'strdup' [-Werror=implicit-function-declaration]
lumberjack.c:159:36: error: assignment makes pointer from integer without a cast [-Werror]
lumberjack.c:168:29: error: assignment makes pointer from integer without a cast [-Werror]
lumberjack.c:185:48: error: assignment makes pointer from integer without a cast [-Werror]
lumberjack.c:187:50: error: assignment makes pointer from integer without a cast [-Werror]
lumberjack.c:191:9: error: format '%s' expects argument of type 'char *', but argument 6 has type 'int' [-Werror=format]
lumberjack.c:221:3: error: format '%s' expects argument of type 'char *', but argument 6 has type 'int' [-Werror=format]
cc1: all warnings being treated as errors
gmake: *** [lumberjack.o] Error 1

The dependencies in vendor/ build mostly fine. (I skipped libuuid, zeromq builds fine without it, jemalloc had a few issues, but I think I solved those).

**Comment by jordansissel** [comment]
﻿﻿﻿﻿﻿﻿

I think this bug was for the C version of lumberjack, lsf is now in Go; I'm not sure it's affected anymore. Please reopen if you're still hitting this in the newer logstash-forwarder.

Go unfortunately does not support HP-UX, to my knowledge.
