### ISSUE TITLE
forwarder infinite loop THIS IS PROBABLY A DUPLICATE OF #164 Bug

### ISSUE THREAD

**Issue by dasibre** [elasticsearch/logstash-forwarder#203]
THIS IS PROBABLY A DUPLICATE OF #164 Bug for log lines without or delayed newlines results in a file truncated detection and reading the file again

I am having an identical problem, completely making logstash-forwarder unusable, 
 
My forwarder gets stuck in an infinite loop when dealing with alot of events.
I get the following in the logstash-forwarder logs
2014/05/07 09:53:02.166995 Registrar received 1024 events
2014/05/07 09:53:02.591558 Registrar received 1024 events
2014/05/07 09:53:06.046122 File truncated, seeking to beginning: /data/logs/tomcat/current
2014/05/07 09:53:06.522043 Registrar received 1024 events
2014/05/07 09:53:06.989197 Registrar received 1024 events
2014/05/07 09:53:07.456654 Registrar received 1024 events
2014/05/07 09:53:07.990204 Registrar received 1024 events
2014/05/07 09:53:08.456857 Registrar received 1024 events
2014/05/07 09:53:11.695019 File truncated, seeking to beginning: /data/logs/tomcat/current
2014/05/07 09:53:12.170762 Registrar received 1024 events
2014/05/07 09:53:12.622887 Registrar received 1024 events
2014/05/07 09:53:13.060649 Registrar received 1024 events
2014/05/07 09:53:13.505549 Registrar received 1024 events
2014/05/07 09:53:17.467030 File truncated, seeking to beginning: /data/logs/tomcat/current
2014/05/07 09:53:17.970150 Registrar received 1024 events
2014/05/07 09:53:18.439627 Registrar received 1024 events
2014/05/07 09:53:18.910519 Registrar received 1024 events
2014/05/07 09:53:19.376521 Registrar received 1024 events
2014/05/07 09:53:19.803628 Registrar received 1024 events

I noticed there are many pull requests associated with this similar problem, is there one particular solution to this bug that's been merged yet?

**Comment by jordansissel** [comment]
I think this is resolved? Please reopen if not.

**Comment by jordansissel** [comment]
(master branch, 0.4.0 release coming soon)
