### ISSUE TITLE
Will there be a new release?

### ISSUE THREAD

**Issue by dwerder** [elasticsearch/logstash-forwarder#210]
Hi guys,

i was curios if  a new release is on the road, because there are big branches of driskell and joubin. Will they be merged, because they have lots of fixes.

Greetz

**Comment by jordansissel** [comment]
I am working on a release now (0.4.0). It passed all tests today. Hopefully have a release bundled up soon. Still much work to do (write a blog post, write a changelog, etc), but we're close.
