### ISSUE TITLE
Virtual memory size on windows is 35GB

### ISSUE THREAD

**Issue by kozyarchuk** [elasticsearch/logstash-forwarder#214]
Hi,
   I am using logstash-forwarder-0.3.1 on windows 7.   From process explorer, I can see virtual size reported as 35,793,828KB. ( Private bytes and Working set are much more reasonable and are under 100,000KB).

**Comment by jordansissel** [comment]
virtual address size isn't necsesarily "consuming ram" or memory space, as @driskell noted.
