### ISSUE TITLE
Users are being punished by Go's 1.3 TLS changes.

### ISSUE THREAD

**Issue by jordansissel** [elasticsearch/logstash-forwarder#226]
Most (especially new) lsf users start with self-signed certs.

For these certs, there is no value in requiring a ServerName (CN or IP) check, yet in Go 1.3 they made CN/IP checks mandatory.

Remediation:
1) Fork Go's tls package immediately. Patch it so that server name checks are *not* enforced if the server cert is self-signed. We must still do cert validation, just skip the string equality nonsense.
2) Propose this change upstream to Go hopefully in time for Go 1.4 or 1.5

cc @alphazero-es - Thoughts?

**Comment by adamenger** [comment]
I'm also experiencing this issue on Go 1.4.1 and latest master. I think the biggest failure here is that the documentation hasn't been updated to reflect this issue and it's over 6 months old. As a newcomer to the project, I can't just download and build the latest source without running into this issue.

I've tried running the OpenSSL commands provided in the README.md but I keep stumbling upon "Failed to tls handshake with 10.0.0.9 x509: certificate is valid for , not my.subdomain.com". It seems that the recommended fix in this thread is to insecurely generate a certificate which trusts anything, is that really what I should be doing?

**Comment by jordansissel** [comment]
> It seems that the recommended fix in this thread is to insecurely generate a certificate which trusts anything

I do not recommend generating insecure certificate configurations. You must generate a cert with a valid subject (CN or IP SAN, depends on your situation) to be accepted.

**Comment by jordansissel** [comment]
> I think the biggest failure here is that the documentation hasn't been updated to reflect this issue and it's over 6 months old

The creation and management of SSL certificates is far outside the scope of things I want to maintain and debug across 10 different operating systems and vendors.

However, I have now added this: https://github.com/elasticsearch/logstash-forwarder/commit/0e22bad95b0c40b19d0e7738344e3bc184f08362

**Comment by blalor** [comment]
It would be helpful if that also pointed out that you can do `*.*.*.*` to match any IP address.

**Comment by driskell** [comment]
@blalor Such common name will likely not match IP address. The certificate layout specifically has a separate section for IP SAN entries, and deliberately ignores the common name and DNS SAN entries if connecting via IP. This is the main issue people are having in this ticket - adding the IP SAN entries is not straight forward with openssl commands.

**Comment by adamenger** [comment]
>The creation and management of SSL certificates is far outside the scope of things I want to maintain >and debug across 10 different operating systems and vendors.

@jordansissel I agree and sorry if my first comment sounded curt, I was frustrated after battling the TLS issue for a few hours :). Still not up and running yet, but I will report back with what does end up working so I can help others with the same issue.

Thanks for your work on this..it's the only logshipper that's worked for me and satisfied my requirements.

**Comment by adamenger** [comment]
Alright, to confirm @jordansissel the new command you've placed in the documentation solved the cert error with Go 1.4 and LFS latest master. 

Thanks for adding that. To others who find themselves with this issue,  generating certs with the updated documentation in this commit https://github.com/elasticsearch/logstash-forwarder/commit/0e22bad95b0c40b19d0e7738344e3bc184f08362 fixed it for me.

**Comment by lesaux** [comment]
Hello, I hadn't played around with logstash in a while and was confronted to this issue as well. I'm using an ip address for the logstash server in the logstash-forwarder config. 
You can add an IP SAN by adding
subjectAltName = IP:192.168.2.107  (replace with the ip of your logstash server)
in the [v3_ca] section of your openssl.cnf file before generating certs.
I believe SAN extension in req -new can only be done from openssl config file, but correct me if I'm wrong.

**Comment by jordansissel** [comment]
I'm closing.

The correct solution is to generate certificates with an appropriate CN or IP SAN (Depending on your situation).
