### ISSUE TITLE
Older Linuxes

### ISSUE THREAD

**Issue by zeraholladay** [elasticsearch/logstash-forwarder#240]
My environment has a few CentOS/RedHat 5.6 hosts running 2.6.18 kernels.  According to the Go doc at http://golang.org/doc/install, Go is only supported on 2.6.23 or later.  Has anyone had any luck build LSF for older Linuxes (if so, how did you do it)?  The obvious solution is to upgrade the kernel, but I'm curious if anyone has experience in this domain.

**Comment by jordansissel** [comment]
As we are limited to what Go supports ,best recommendation is to "try it and see". If it works, cool. If not, there's little to be done.
