### ISSUE TITLE
packaging can be a pain

### ISSUE THREAD

**Issue by FlorinAndrei** [elasticsearch/logstash-forwarder#284]
Using the fpm gem sounds like a good idea, but my first experience with it and logstash-forwarder was frustrating. I tried to package this software on Ubuntu 14.04.

First off, "gem install fpm" failed mysteriously, until I realized I also need to install the ruby-dev package. Just plain ruby is not enough. Not having any experience with Ruby before, the error messages were not helpful. But eventually I stumbled upon https://github.com/jordansissel/fpm which suggested to install ruby-dev, which I did, and the gem then installed correctly.

Then "make deb" within logstash-forwarder failed complaining about the Go version, it needs at least 1.3. My version was:

go version xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1 linux/amd64

Again, mystery. 4.9.1 is bigger than 1.3, right? Until I asked on IRC #go-nuts and they told me that's gccgo, while I need golang. So I went and installed the golang package, only to realize it's version 1.2, while this software requires 1.3

Again, #go-nuts to the rescue, I was instructed to download the binary golang tar.gz from https://golang.org/dl/ and use that instead.

Finally, success. I was able to build logstash-forwarder_0.3.1_amd64.deb on Ubuntu 14.04

I appreciate that someone made the effort to make packaging easier, but in practice it's quite tricky. The various moving parts involved in the process have strange non-standard requirements, and that makes the process a lot more complicated than it should.

This is not meant to be a "please fix this bug" type of message, but more like a comment, a "here's my story" type of thing from the perspective of someone who is just beginning to start using this software.

I'm now looking forward to start using logstash-forwarder, as it promises to be quite useful based on what I've read so far.

Thank you.

**Comment by krinkere** [comment]
+1 on this

**Comment by grahamrhay** [comment]
what ruby version is required for the build? mustache demanded >= 2.0.0, but with 2.2.0 I get an error from pleaserun:

```
11:54:15 pleaserun --install --no-install-actions --install-prefix ./build \
11:54:15 		--overwrite -p sysv -v lsb-3.1 /opt/logstash-forwarder/bin/logstash-forwarder 
11:54:15 /var/lib/jenkins/.rvm/gems/ruby-2.2.0-preview1@logstash-forwarder/gems/pleaserun-0.0.9/lib/pleaserun/cli.rb:145:in `setup_defaults': undefined method `name=' for #<PleaseRun::CLI:0x00000001f157b0> (NoMethodError)
11:54:15 	from /var/lib/jenkins/.rvm/gems/ruby-2.2.0-preview1@logstash-forwarder/gems/pleaserun-0.0.9/lib/pleaserun/cli.rb:107:in `execute'
11:54:15 	from /var/lib/jenkins/.rvm/gems/ruby-2.2.0-preview1@logstash-forwarder/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
11:54:15 	from /var/lib/jenkins/.rvm/gems/ruby-2.2.0-preview1@logstash-forwarder/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
11:54:15 	from /var/lib/jenkins/.rvm/gems/ruby-2.2.0-preview1@logstash-forwarder/gems/pleaserun-0.0.9/bin/pleaserun:6:in `<top (required)>'
11:54:15 	from /var/lib/jenkins/.rvm/gems/ruby-2.2.0-preview1@logstash-forwarder/bin/pleaserun:23:in `load'
11:54:15 	from /var/lib/jenkins/.rvm/gems/ruby-2.2.0-preview1@logstash-forwarder/bin/pleaserun:23:in `<main>'
11:54:15 	from /var/lib/jenkins/.rvm/gems/ruby-2.2.0-preview1@logstash-forwarder/bin/ruby_executable_hooks:15:in `eval'
11:54:15 	from /var/lib/jenkins/.rvm/gems/ruby-2.2.0-preview1@logstash-forwarder/bin/ruby_executable_hooks:15:in `<main>'
```

it was working before with 1.9.3 & just fpm, is this a recent change?

**Comment by zaniyah** [comment]
The docs also need you to install the pleaseinstall ruby gem, as that is a non-obvious error when things don't work.

I also found that the RPM includes a config file in /etc/default/  -- this directory is debian-specific.  On RedHat-derivatives it should be using /etc/sysconfig/ instead.

**Comment by grahamrhay** [comment]
(or bundle install)

**Comment by driskell** [comment]
@zaniyah Usually both exist and both are used. Default is used for default settings for all instances. Sysconfig is used for instance specific settings. So for tomcat you have one in default and (potentially) multiple in sysconfig if multiple tomcat instances.

So both are used as far as I know but may differ. I know on my RedHat systems both are in use.

**Comment by driskell** [comment]
@zaniyah A quick research though and it could go either way. Might be my tomcat items just happen to work like that. But it does seem other upstreams use /etc/default too. It seems mostly that upstream config files (like here) can get put in /etc/default but Fedora prefers directly in /etc, and that sysconfig should only be used for distribution specific config that is not from upstream. Not as clear as I thought sorry!

**Comment by jordansissel** [comment]
> go version xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1 linux/amd64

I *strongly* recommend not using gccgo to build this project especially if you intend to use `make deb`. #386 has references on why.

**Comment by jordansissel** [comment]
> First off, "gem install fpm" failed mysteriously, until I realized I also need to install the ruby-dev package

I've updated the notes for #386 to include mention of how to get a functioning Ruby installation on OS distributions that ship an incomplete ruby (red hat, debian, etc)

**Comment by jordansissel** [comment]
#386 is merged.

**Comment by jordansissel** [comment]
Hopefully the readme is more clear. If we are missing specific details for certain OS distributions, a new ticket per problem/platform would be lovely. Thanks all! :)

**Comment by grahamrhay** [comment]
using rvm 2.0.0 worked for me, looks like the 2.2.0 is a preview version which has some incompatibility
