### ISSUE TITLE
json escaping broken

### ISSUE THREAD

**Issue by zabbal** [elasticsearch/logstash-forwarder#313]
I'm trying to ship logs to logstash and got escaping partially broken:

I receive:
{
  "message": "{\"timestamp\":\"2014-11-18T09:18:24.491215\",\"event_type\":\"dns\",\"src_ip\":\"8.8.8.8\",\"src_port\":53,\"dest_ip\":\"192.168.2.11\",\"dest_port\":41498,\"proto\":\"UDP\",\"dns\":{\"type\":\"answer\",\"id\":20378}}",
  "@version": "1",
  "@timestamp": "2014-11-18T08:18:26.355Z",
  "type": "SuricataIDPS-logs",
  "file": "/var/log/suricata/eve.json",
  "host": "suricata",
  "offset": "84002382"
}

while in logstash-shipped logs it's properly parsed:

{
  "timestamp": "2014-11-18T09:16:00.266211",
  "event_type": "alert",
  "src_ip": "192.168.42.104",
  "src_port": 5601,
  "dest_ip": "192.168.42.129",
  "dest_port": 45360,
  "proto": "TCP",
  "alert.action": "allowed",
  "alert.gid": 1,
  "alert.signature_id": 2200074,
  "alert.rev": 1,
  "alert.signature": "SURICATA TCPv4 invalid checksum",
  "alert.category": "",
  "alert.severity": 3,
  "@version": "1",
  "@timestamp": "2014-11-18T08:16:00.266Z",
  "type": "SuricataIDPS-logs",
  "host": "selks",
  "path": "/var/log/suricata/eve.json"
}

Hence I suspect the broken escaping comes from forwarder. Is this a known issue?
Is there workaround for that?

On the receiving end I have lumberjack input configured, the only filtering I have is about timestamp -> iso8601, on the sending end I have "path" and "fields" with the type corresponding to the one on receiving end.

Shall I explicitly add some codec somewhere or some forwarder-specific filtering?

**Comment by cod3fr3ak** [comment]
Is this still an issue? I have a node dev that wants to throw logs in json format. I run the logstash-forwarder on the server in question will I need any special hacks to make sure his data comes across the pipe.

**Comment by zabbal** [comment]
works for me now - apparently it was kibana issue which was hard to diagnose

**Comment by cerw** [comment]
Hi how can I combine JSON (Suricatal) and Plain (syslogs, apache) all togehter? I have tried applied filret to only decode by type, but nothing seem to work. 

Petr

**Comment by nikitsaraf** [comment]
Hey @zabbal I am facing similar issue to the one you have faced. The JSON is not getting escaped properly. It would be great, if you could help me with what was the issue with Kibana, so that I could fix the same.

**Comment by astrobounce** [comment]
Hey @zabbal i am facing similar issue , LSF - LS - ES this is my architecture .

at LSF side i am using multiple file path option . so basically i am parsing apache access log as well as custom app log in json format , to seperate them I have used type tag type "apache" , type "json"

"files": [
    {
      "paths": [ "/var/log/httpd/access_log" ],
      "fields": { "type": "apache" }
    },
   {
      "paths": [ "/home/arvind/logs/app_logs.txt" ],
      "fields": { "type": "json" }
    }

  ]


at LS side 

in filter section i have used filter {
  if [type] == "apache" {
    grok {
      pattern => "%{COMBINEDAPACHELOG}"
    }
  }
  if [type] == "json" {
  json {
        source => 'message'
     }
}
}

Apache logs are processed fine and shown in proper format , but for json logs it is showing _jsonparsefailure .


Please help as i am not able to fix this .

Thanks 
astro

**Comment by zabbal** [comment]
Well, in my particular case this issue went away after I've updated to recent kibana version. And I have no idea how could it be diagnosed properly. That and lack of supported Debian repo makes us consider https://github.com/driskell/log-courier for our deployment. Unfortunately it does not have deb repo as well so we're in flux ATM but from the feature description it seems like LC could help with some of the codec issues people are facing.

**Comment by rabidscorpio** [comment]
@astrobounce I have the exact same issue, I haven't even tried using the json filter because I'm also sending syslog, nginx and other events over lumberjack as well.  I'm not even getting the _jsonparsefailure, events just seem to vanish.

**Comment by astrobounce** [comment]
@rabidscorpio I have worked on this , and found the way , its working fine for me ,

At logstash server side 

in filter section add these lines .

if [type] == "json" {
	json {
		source => "message"
	}
    }

At log forwarder side use this code .

"files": [
    {
      "paths": [ "/path_to_log" ],
      "fields": { "type": "json" }
    }

  ]

Logstash version is 1.4.2
and logstash forwarder version is 0.3.1
