### ISSUE TITLE
Address option unused in lumberjack/server.rb

### ISSUE THREAD

**Issue by joes** [elasticsearch/logstash-forwarder#326]
I found this issue when trying to use the `host` option for the lumberjack input in logstash:

```
input {
  lumberjack {
    host => "myhost.com"
    #...
  }
}
```
This option does not seem to have any effect. Using netstat I can see that the input is listening on all network interfaces on the server.

The problem seems to be that the lumberjack input uses the server class (https://github.com/elasticsearch/logstash-forwarder/blob/master/lib/lumberjack/server.rb) from this project. This class defines an address-option but this option is never used by this class internally when it creates the TCPServer instance.

```ruby
module Lumberjack
  class Server
    attr_reader :port

    # Create a new Lumberjack server.
    #
    # - options is a hash. Valid options are:
    #
    # * :port - the port to listen on
    # * :address - the host/address to bind to
    # * :ssl_certificate - the path to the ssl cert to use
    # * :ssl_key - the path to the ssl key to use
    # * :ssl_key_passphrase - the key passphrase (optional)
    def initialize(options={})
      @options = {
        :port => 0,
        :address => "0.0.0.0",
        :ssl_certificate => nil,
        :ssl_key => nil,
        :ssl_key_passphrase => nil,
      }.merge(options)
      #... omitted code
      @tcp_server = TCPServer.new(@options[:port])
      #... omitted code
  end
   #... omitted code
end

**Comment by suyograo** [comment]
Fixed via #363
