### ISSUE TITLE
logstash-forwarder: command not found

### ISSUE THREAD

**Issue by DavidAwad** [elasticsearch/logstash-forwarder#336]
Hi, I'm runnning the installation for logstash forwarder and I was hung up on this step. 

`logstash-forwarder -config logstash-forwarder.conf`

I get the error `logstash-forwarder: command not found`. So i'm wondering, should I make it executable MYSELF or has something gone wrong in my installation already?

**Comment by hartfordfive** [comment]
Did you install it by cloning the repo and then running "go build" within it?  If so, you'll need to run "./logstash-forwarder -config logstash-forwarder.conf" in the directory as the command most likely isn't in any directories of your $PATH environment variable.  You could either copy the binary file to "/usr/sbin" or simply symlink it in that directory, but make sure that "/usr/sbin" is present in your $PATH.

**Comment by DavidAwad** [comment]
i figured that one out. it was basically me being dumb. you were totally right. Thanks!
