### ISSUE TITLE
tls - problems with current version

### ISSUE THREAD

**Issue by rogerthat** [elasticsearch/logstash-forwarder#341]
hi,

i had some tls-problems with a very recent version and had to revert to 6082bd8aaecb2180f5b56f4fb1b2940a6935ef7b

logstash: 1.4.2 (download from the site)
logstash-forwarder: HEAD  (github)

error:

Failed to tls handshake with local error: protocol version not supported

i tried different java/jdk/jre - versions and many -Dhttps - switches but no positive result

the bug is more in logstash itself since it doesnt support tls 1.1/1.2 

java -jar logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar -v
jruby 1.7.11 (1.9.3p392) 2014-02-24 86339bb on Java HotSpot(TM) 64-Bit Server VM 1.8.0_25-b17 +indy [linux-amd64]

testssl - output:

 SSLv2      Local problem: /usr/bin/openssl doesn't support "s_client -ssl2" 
 SSLv3      offered (NOT ok) 
 TLSv1      offered (OK) 
 TLSv1.1    not offered
 TLSv1.2    not offered
 SPDY/NPN   not offered

when going back to 6082bd8aaecb2180f5b56f4fb1b2940a6935ef7b everything seems fine

cheers, 

mex

**Comment by jordansissel** [comment]
I've reverted the TLS 1.1 change.

**Comment by jordansissel** [comment]
I can confirm that:
* Logstash master server hello reports TLS v1.1
* Logstash 1.4.2 server hello reports TLS v1.0

**Comment by jordansissel** [comment]
I'm going to close this sinc eI reverted the change. Further discussion will happen here: https://github.com/elasticsearch/logstash/issues/2328
