### ISSUE TITLE
Listen on socket

### ISSUE THREAD

**Issue by johntdyer** [elasticsearch/logstash-forwarder#345]
Hello,  

 I have a few questions:

* Is there any way to have the forwarder listen on a socket and forward that ?   
*  if I am reading from a file, which is writing and rolling quickly, how do I know how far behind I am ? 

thanks

**Comment by jordansissel** [comment]
> Is there any way to have the forwarder listen on a socket

Not at this time. Some alternative solutions:
1) Use netcat and pipe to logstash-forwarder. If you set lsf up with ` { "files": [ { "paths": [ "-" ] } ] }` it will read from stdin, so you can do: `nc -l 12345 | ./logstash-forwarder ...`

**Comment by jordansissel** [comment]
> how do I know how far behind I am?

This information is not currently made available, though we could add it eventually.

**Comment by jordansissel** [comment]
Hopefully I answered your questions :)
