### ISSUE TITLE
Docker use case, syslog/cron/logrotate and data loss

### ISSUE THREAD

**Issue by weedcoder** [elasticsearch/logstash-forwarder#348]
I use ELK.
I use docker for softwares that produces outputs / logs.
logstash-forwarder "harvests" log files wich are on a docker container shared volume.
docker containers that produces logs don't rotate them.

i don't want to use syslog() because unix domain sockets are outdated.
i want to use 1>> and 2>> redirections to produce log files.
i don't want to use logrotate because redirections doesn't support closing/reopening log file mechanism, truncation will eventually lead to data loss and it implies crontab somehow.

The "harvest" job of a lumberjack means he removes logs from the log files.
logs exist in ELK, docker container data are ephemeral.

So, to replace syslog/cron/logrotate wich docker avoids, logstash-forwarder could have a "forwarded logs consuming" feature.

**Comment by weedcoder** [comment]
btw, if it's not obvious, without this log consumption or rotation, log files will grow endlessly

**Comment by jordansissel** [comment]
> The "harvest" job of a lumberjack means he removes logs from the log files.

Files can't be truncated "from the front" so if you are only appending to a file using shell redirection `>>` and `2>>` then the only rotation mechanism available is to truncate the file which can lose data given the non-atomic operation (writing in a different process than truncation).

Instead of writing to a file with no mechanism for curating old logs, you can do something different. logstash-forwarder lets you read from stdin. This will let you pipe the output of your program to logstash-forwarder directly `./my-app | logstash-forwarder ...`

**Comment by driskell** [comment]
> i don't want to use logrotate because redirections doesn't support closing/reopening log file mechanism, truncation will eventually lead to data loss and it implies crontab somehow.

I wrote a script to enable this, loggerfile.py
It writes the stdin to a log file but allows reopening of the log file without loss of data:
https://github.com/driskell/loggerfile/blob/master/README.md
(There's a pure bash version too but I plan to remove it and stick to Python if I do any more updates)

This way you never lose logs. Piping to forwarder is possible too but if logstash is down logs are buffered and lost if forwarder fails. With sending to log file you at least get resume if forwarder restarted and less chance of loss.

I use loggerfile with my logstash init scripts. I run the reopen logs with a logrotated configuration

**Comment by weedcoder** [comment]
@jordansissel yes, the piping method can be a solution but i run several containers in order to have only one process per container. piping will invole one more process for each one. This is why these containers mount the /var/log volume from a logstash-forarder container

@driskell same issue, one more process per container.

I'm working on a solution of a single container that expose a log volume, forwarding and flushing the content.
The purpose is to do:
```Shell
docker run --name logstash-forwarder -v /var/log logstash-forwarder /path/to/logstash-forwarder
docker run --volumes-from logstash-forwarder mydockerimage /path/to/myapp 1>>/var/log/myapp.log 2>>myapp.err.log
```

**Comment by driskell** [comment]
@weedcoder I think here the only solution is to have the daemon itself implement log files and also implement log file maintenance so it can, at the very least, reopen its log files. If this cannot be done the only way I know is to have the output stream handled by another process.

Whether that be loggerfile to implement the reopen with cronned logrotated for the remainder of the maintenance, or forwarder. (Though if logstash goes down there's no buffer except memory and if the container stops logs are lost)

If the application does not log to file and provide minimal requirement for log file maintenance something else has to. If there is another way, I'm certainly interested though as I have had to use loggerfile myself in places and replacing that extra process is worthwhile if it simplifies configurations. I can't see it though.

Jason

**Comment by weedcoder** [comment]
@driskell you're right., there are not many way to do it.
The app has to implement logging to files with reopen and the system has to use logrotate to control log growth.
I think i'll look at your loggerfile :+1:  to address this.

There is no reliable tool to throw dockerized applications output and error to forwarder (ELK)

Maybe something to do here, inspired by https://github.com/tytso/e2fsprogs/blob/master/misc/logsave.c

**Comment by jordansissel** [comment]
There are solutions, and it feels like you aren't giving a clear description of your requirements and constraints, so from my view, it seems like you're cherry picking reasons not to use every single approach provided.

Nothing is perfect :)

If you pipe to lsf, you might block your app. If you log to a disk and forward asynchronously, you will lose data under certain conditions or you can block your app due to a stall in the vfs layer.

> There is no reliable tool to throw dockerized applications output and error to forwarder

The "pipe to forwarder" is what Heroku did (when I worked there), fwiw, for all user apps, and it works well. I don't know your requirements, so I can't really offer any further information.

**Comment by weedcoder** [comment]
I have some restful api applications which write to standard output and standard error.
these applications run with supervisord, outputs are caught and delivered to syslog.
a reverse proxy nginx can be used to balance requests on a set of listening processes 
a memcached can be a part of it

constraints:
I want to use docker, one process/container, get rid of supervisord, have containers for n applications, 1 lsf, 1 nginx and 1 memcached.
i was planning to redirect applications outputs to shared docker volumes for lsf and use docker links for nginx and memcached.

the tricky things are redirections doesn't support file reopening, truncation loose data and logs grow without rotation.
pipe can be used but out/err aren't treated differently and it implies one more process/container
@driskell implemented a file reopen feature, allowing rotation.
