### ISSUE TITLE
Protocol not considered in README.md

### ISSUE THREAD

**Issue by sam-falvo** [elasticsearch/logstash-forwarder#35]
In the README, you list several popular protocols which fail to meet your needs.  However, the BEEP protocol might be what you're looking for.  See http://en.wikipedia.org/wiki/BEEP as a starting point.

**Comment by jordansissel** [comment]
For now, the lumberjack protocol is fine enough. It has some warts, but it does the job. I'll consider BEEP in the future if we need to revise or scrap the current protocol.

Thanks! :)
