### ISSUE TITLE
Ruby client uses incorrect max sequence number?

### ISSUE THREAD

**Issue by jwalton** [elasticsearch/logstash-forwarder#354]
My ruby is a little rusty, but I was looking at [this line](https://github.com/elasticsearch/logstash-forwarder/blob/master/lib/lumberjack/client.rb#L8), and when I pop this into `irb`, I get back:

    1.9.3-p385 :001 > SEQUENCE_MAX = (2**(0.size * 8 -2) -1)
     => 4611686018427387903

But, sequence numbers are 32 bit unsigned integers (according to [this](https://github.com/elasticsearch/logstash-forwarder/blob/master/PROTOCOL.md#data-frame-type)) so this can't possibly be correct.

**Comment by jordansissel** [comment]
Yep; will need to fix this. I think we also don't have tests to cover sequence rollover. Thanks for reporting!

**Comment by jordansissel** [comment]
This is addressed in #362

**Comment by suyograo** [comment]
Fixed in https://github.com/elasticsearch/logstash-forwarder/pull/362
