### ISSUE TITLE
-Version missing?

### ISSUE THREAD

**Issue by epinault** [elasticsearch/logstash-forwarder#356]
It would be nice to have a -version so we know what version was installed?

**Comment by jordansissel** [comment]
At present there are no formal releases of logstash-forwarder so there is no version concept to use. However, I'm working on rolling up a release shortly that will include a version number.

**Comment by epinault** [comment]
Sounds good. Just a number , or a date would work so I know what to compare it to :) thanks!

**Comment by epinault** [comment]
thanks!
