### ISSUE TITLE
Issue when using a folder of config

### ISSUE THREAD

**Issue by epinault** [elasticsearch/logstash-forwarder#357]
So I tried to use it per the doc where it says we can use a folder (though no examples).

I am running

```
 /opt/logstash-forwarder/bin/logstash-forwarder -config /etc/logstash-forwarder.d/ -spool-size 100 -log-to-syslog
```

and getting

```
2015/01/26 20:53:28 publisher init
2015/01/26 20:53:28 
2015/01/26 20:53:28 Failed unmarshalling json: invalid character '\x00' looking for beginning of value
```

Each file load individually correctly (there are 3 and it works when I point manually to each of them. So what am I doing wrong? Since there is no version information in the binary it is hard to tell if this was a feature added after the code I am running 

any idea?

**Comment by epinault** [comment]
I think I took a version just prior to that commit but just a guess since I cannot tell what version was installed  
https://github.com/elasticsearch/logstash-forwarder/commit/a1fe078042a33788d63d34d16d7ee94b23b1a18f#diff-b4bda758a2aef091432646c354b4dc59

**Comment by epinault** [comment]
Actually I seem to have the latest version... Based on the Makefile and the package installed. it says

Version: 0.3.1


So I am not able to load a folder base configuration unless that code has not yet been merged into the debian package?

**Comment by jordansissel** [comment]
@epinault the deh package is quite old because we have not done a release in quite some time. It is recommended that you buidl from source in the master branch of this repository.

**Comment by jordansissel** [comment]
If you still have this problem with a build from the master branch, can you include the output of `ls -al /etc/logstash-forwarder.d/` ?

**Comment by epinault** [comment]
Sounds good. I ll build it from master and will let you know

**Comment by jordansissel** [comment]
Cool. Sorry for the confusion :)

**Comment by phinze** [comment]
fwiw I just hit this too building from the package hosted on the deb package repo

**Comment by epinault** [comment]
Maybe put a note in the README about the package state?

**Comment by jordansissel** [comment]
I don't know how y'all found the deb package, but I have now deleted it.

@epinault I have deleted the logstash-forwarder package from the repository, so that should solve this without needing to update the README.

**Comment by phinze** [comment]
> I don't know how y'all found the deb package...

I got it from here:

https://github.com/elasticsearch/puppet-logstashforwarder/blob/master/manifests/repo.pp

If there are no official package repos, perhaps that project needs to be changed to always build from source?

**Comment by jordansissel** [comment]
#385 is tracking the package repository. Otherwise I think this ticket is resolved.

**Comment by epinault** [comment]
yup, working for me!
