### ISSUE TITLE
Make RPM init-script Broken?

### ISSUE THREAD

**Issue by ninjada** [elasticsearch/logstash-forwarder#374]
Getting the following error after gem install fpm; make rpm

------------------
pleaserun --install --no-install-actions --install-prefix ./build \
		--overwrite -p sysv -v lsb-3.1 /opt/logstash-forwarder/bin/logstash-forwarder 
make: pleaserun: Command not found
make: *** [generate-init-script] Error 127
------------------

Successfully made an rpm a couple of days ago, on inspecting the Makefile, seems to be some large changes but I could be wrong. Is it fine to use the previous Makefile and Makefile.ext?

Deploying for RHEL/CentOS/AmazonLinux. Using an old RHEL RPM but experiencing connection reset EOF / ACK errors continuously in logstash-forwarder log, so figured I'd build a new RPM off the latest version but....

**Comment by rabidscorpio** [comment]
@ninjada definitely broken, it was just updated today.  I had to install rbenv to compile and install a new version of ruby >= 2.0 (for mustache), install "pleaserun" and then edit the makefile to explicitly put the path to the "pleaserun" command.  Even then, it had no effect on my problem ("Read error looking for ack: EOF").

**Comment by aranw** [comment]
Has anyone got a fix for this, I've tried installing logstash-forwarder using the deb source url which has obviously been pulled as mentioned in #370. I've then tried to build the package myself and package it into a deb file but that seems to be now broken as well?

**Comment by jordansissel** [comment]
Scott, eof on a read is a problem caused by the remote side (logstash) or a
network interruption. I doubt it had anything to do with lsf (wothout more
data to the contrary) and certainly seems unlikely to have much to do with
how lsf is packaged.

**Comment by krinkere** [comment]
Just tried to run it on Ubuntu 12.4 and received the following

make deb
go build
pleaserun --install --no-install-actions --install-prefix ./build \
		--overwrite -p sysv -v lsb-3.1 /opt/logstash-forwarder/bin/logstash-forwarder 
make: pleaserun: Command not found
make: *** [generate-init-script] Error 127


Also tried on Centos 6.4 to make rpm

got same message
logstash-forwarder]$ make rpm
pleaserun --install --no-install-actions --install-prefix ./build \
		--overwrite -p sysv -v lsb-3.1 /opt/logstash-forwarder/bin/logstash-forwarder 
make: pleaserun: Command not found
make: *** [generate-init-script] Error 127

**Comment by erkrnt** [comment]
Possible workaround:

Verify the 'pleaserun' gem is installed as a dependency before running 'make deb'. I was trying to build it and noticed I didn't have the gem. Installed and worked, included commands and output below.

gem install fpm pleaserun
go build
make deb

```
pleaserun --install --no-install-actions --install-prefix ./build \
		--overwrite -p sysv -v lsb-3.1 /opt/logstash-forwarder/bin/logstash-forwarder 
No name given, setting reasonable default based on the executable {:name=>"logstash-forwarder", :level=>:warn}
Writing file {:destination=>"./build/etc/init.d/logstash-forwarder"}
Writing file {:destination=>"./build/etc/default/logstash-forwarder"}
fpm -f -s dir -t deb -n logstash-forwarder -v 0.4.0 \
		--architecture native \
		--replaces lumberjack \
		--description "a log shipping tool" \
		--url "https://github.com/elasticsearch/logstash-forwarder" \
		./logstash-forwarder=/opt/logstash-forwarder/bin/ \
		./build/=/
Created package {:path=>"logstash-forwarder_0.4.0_amd64.deb"}
```

sudo dpkg -i logstash-forwarder_0.4.0_amd64.deb 

```
(Reading database ... 93207 files and directories currently installed.)
Preparing to unpack logstash-forwarder_0.4.0_amd64.deb ...
Unpacking logstash-forwarder (0.4.0) over (0.3.1) ...
Setting up logstash-forwarder (0.4.0) ...
Processing triggers for ureadahead (0.100.0-16) ...
```

Hope it helps.

**Comment by MarkGavalda** [comment]
Thanks @erkrnt I ran into the same problem. And of course in order to install pleaserun you'll have to install mustache which requires Ruby > 2.0, and by default Ubuntu 14.04 comes with 1.9...

**Comment by ninjada** [comment]
moved my rhel rpm build environment onto latest ruby 2.2.0, so i could get pleaserun working and everything worked ok from there.

**Comment by srai09** [comment]
I get this error installing pleaserun,
gem install pleaserun
ERROR:  Error installing pleaserun:
        mustache requires Ruby version ~> 2.0.

Ruby is already at 2.0
root@web01:~# ruby -version
ruby 2.0.0p481 (2014-05-08 revision 45883) [x86_64-linux]
