### ISSUE TITLE
Alternative with less dependencies

### ISSUE THREAD

**Issue by objectiveSee** [elasticsearch/logstash-forwarder#380]
This project has a lot of dependencies (go, ruby, etc) and takes a lot of steps to configure.  Is there a comparable alternative to this project which still runs as a daemon?

**Comment by driskell** [comment]
In fact this program has no dependencies (in theory). They are only build dependencies.

Once the repositories are back it should be straight forward to use again.

**Comment by jordansissel** [comment]
This project has no runtime dependencies. Ruby is not required for running. Go is not required for running.

Go is required for compiling. Ruby is used for packaging, but is not required.
