### ISSUE TITLE
DEB dependency on libgo5 not met

### ISSUE THREAD

**Issue by untergeek** [elasticsearch/logstash-forwarder#383]
Propose making the deb, at least, dependent on `libgo5`, based on this experience.

## Install
```
$ sudo dpgk -i logstash-forwarder_0.4.0_amd64.deb
```

## Run
```
$ /opt/logstash-forwarder/bin/logstash-forwarder
/opt/logstash-forwarder/bin/logstash-forwarder: error while loading shared libraries: libgo.so.5: cannot open shared object file: No such file or directory
```

## Fix
```
$ sudo apt-get install libgo5
```

## Run again
```
$ /opt/logstash-forwarder/bin/logstash-forwarder
2015/02/20 10:05:45.905529 fatal: config file must be defined
```

**Comment by jordansissel** [comment]
wait, what? Go libraries are static. I have never heard of libgo and don't know what it is and I don't use it myself.

Are you using gccgo or something?

**Comment by jordansissel** [comment]
Googling for libgo finds https://github.com/gcc-mirror/gcc/tree/master/libgo, so I assume you're using gccgo. I have no experience with this project.

I think we should update the docs to require folks use the compiler from the Go project itself.

**Comment by untergeek** [comment]
So do we have a dependency on gccgo or on libgo for the package?  I think it makes sense to use libgo for Ubuntu/Debian as it seems to work and resolve the dependency without adding a compiler.

**Comment by jordansissel** [comment]
The packages we will build (with Jenkins) and release will not use gccgo and have no dependency on libgo.

Here's what it shows on my workstation when I build with the go compiler:

```
% ldd ./logstash-forwarder
        linux-vdso.so.1 =>  (0x00007ffff6dc9000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa3606fc000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa360336000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa360927000)
```

I don't think we should support gccgo since it's one more hassle to deal with. I suspect there is some trapping in Debian that forces gccgo as the compiler, but I don't know since I don't use Ubuntu/Debian's go packages (since they are typically ancient)

**Comment by untergeek** [comment]
So, what then?  Add libgo deps? Or tell users to install it? I'm kind of not sure which direction you're implying there so I wanted to make sure I understand.

**Comment by jordansissel** [comment]
@untergeek I'm not being clear, sorry, let me try -

There are two ways to compile Go. One, with the Go compiler. Two, with gccgo. The go compiler does not have any external dependencies (no libgo). Gccgo links binaries against, and requires, libgo, to provide the Go runtime.

When I build with `go build` it does *not* invoke gccgo and thus has no dependency on libgo.

How are you compiling logstash-forwarder? How did you install Go?

**Comment by untergeek** [comment]
I didn't compile.  I was testing the .deb package and found that it wouldn't work unless I did `apt-get install libgo`.  That's what this ticket is about: trying to figure out how to make the 0.4.0 deb work out of the box.

**Comment by jordansissel** [comment]
How'd you get the .deb package?

**Comment by untergeek** [comment]
From the link @suyograo shared

**Comment by jordansissel** [comment]
@suyograo how did you build this deb? :)

**Comment by suyograo** [comment]
@untergeek @jordansissel I built on ubuntu which probably had `gccgo` installed. I checked out the repo and did `make deb` which uses `go build`

I think we need a new set of artifacts built using the Go compiler

**Comment by suyograo** [comment]
marking this as a doc issue
