### ISSUE TITLE
Running Logrotate on the logstash-forwarder log

### ISSUE THREAD

**Issue by ninjada** [elasticsearch/logstash-forwarder#387]
Hi guys,

Trying to have logrotate run hourly on the latest logstash-forwarder, which generates logstash-forwarder.err & logstash-forwarder.log in /var/log

Just for due diligence on production servers, want to make sure logs don't get out of control over time. I basically only want <12hours of logstash-forwarder logs maximum.

Using the following:

/var/log/logstash-forwarder.* {
    size 1M
    create 640 root root
    rotate 11
    missingok
    notifempty
    sharedscripts
    delaycompress
}

have also tried a postrotate that does logstash-forwarder restart but that doesn't seem as necessary compared to earlier versions that may stop running after a period of time. either way logrotate aint working.

i basically just end up with logstash-forwarder.err.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1 ad infinum ie. doesn't stop at 12 or whatever i set rotate to.

is there any signal to send to logstash-forwarder? can anyone comment on the correct way to rotate the logstash-forwarder log itself?

cheers!

**Comment by driskell** [comment]
Hi @ninjada

It's because your logrotated pattern matches the rotated files too so it's rotating the rotated files. Try this:

```
/var/log/logstash-forwarder.err,
/var/log/logstash-forwarder.log {
size 1M
create 640 root root
rotate 11
missingok
notifempty
sharedscripts
delaycompress
}
```

**Comment by driskell** [comment]
You will need to restart logstash-forwarder in a `postrotate` though as it needs to reopen log files and this can only currently be done by restarting it.

**Comment by ninjada** [comment]
doh. cheers @driskell

**Comment by jordansissel** [comment]
You can avoid restarting by using the `-syslog` flag and having your local syslog daemon manage where the logs are written. Not required, though.
