### ISSUE TITLE
Debian package possible deletes user configuration on upgrade/install

### ISSUE THREAD

**Issue by gebi** [elasticsearch/logstash-forwarder#393]
Hi,

The file `/etc/default/logstash-forwarder` is not marked as config file in the debian package and thus overwrites any changes to this file on install or upgrade time.

Please use --config-files in fpm to mark it as a config file:
```
--config-files CONFIG_FILES   Mark a file in the package as being a config file. This uses 'conffiles' in debs and %config in rpm. If you have multiple files to mark as configuration files, specify this flag multiple times.  If argument is directory all files inside it will be recursively marked as config files.
```

**Comment by jordansissel** [comment]
`/etc/default/logstash-forwarder` is not a user-servicable config file. I will probably get rid of it in the future.

**Comment by gebi** [comment]
That's wrong.
Even the /dev/default/logstash-forwarder your current package provides IS a user-servicable config file, because it's not up to the package to decide under which user logstash-forwarder is executed or eg. in which directory or especially not which config file it is started with per default.

Thus please do not remove the file it is important!
Just mark it as configfile so it does not get bluntly overwritten by the next package update.

eg.
If a user chooses to run logstash-forwarder under another user or with other config files, possible merged from a directory then he has to modify /etc/default/logstash-forwarder.
Currently a user even has to modify the file to get logstash-forwarder to run as the config file option is not set and logstash-forwarder does not start with the provided init script at all.

ps.: please stop to immediately close important issues with wrong explanations when people take their time to report them, that's not considered nice here.

**Comment by amiryal** [comment]
@gebi I pushed a fix to seekingalpha/logstash-forwarder@0f5d32f64a25224a15da1129b64723a79c47e6f2. @jordansissel I will sign the CLA and hopefully you’ll accept my PR eventually. Thank you both!

**Comment by jordansissel** [comment]
> Currently a user even has to modify the file to get logstash-forwarder to run

This was as bug. It has been fixed.
https://github.com/elasticsearch/logstash-forwarder/blob/master/Makefile#L22

**Comment by jordansissel** [comment]
> that's not considered nice here.

"here" ? Please speak only for yourself, otherwise I am going to be confused as to which group you are speaking on behalf of. :(

**Comment by jordansissel** [comment]
> That's wrong.

I'm confused, but I seem to have upset you? I am sorry if this is the case.

The /etc/default/logstash-forwarder file may not stay and is not guaranteed to stay in the future. If you have bugs against the init script, please file them under https://github.com/jordansissel/pleaserun because that is the project that generates them.

**Comment by gebi** [comment]
@jordansissel your /etc/default/logstash-forward is a really important file and as it is changed by your users you should really mark it as config file because otherwise it gets erased on the next package upgrade.

Hm... would you consider including native debian init scripts?

**Comment by amiryal** [comment]
Hi @jordansissel, congratulations and thanks for the v0.4.0 release!

I saw your branch, `packaging-mark-config-files`, where you marked `/etc/logstash-forwarder.conf` as a user-servicable configuration file. That is fine for changing the configuration file, but still leaves no way to customise parameters like `-quiet=true` or `-syslog=true` that would not be overridden on package upgrades.
