### ISSUE TITLE
Logstash-forwarder writes to / and leaks internal state

### ISSUE THREAD

**Issue by gebi** [elasticsearch/logstash-forwarder#397]
Hi,

Please do not write to `/.logstash-forwarder` and leak internal program state public readable to /.
It would be nice to create a directory owned by logstash-forwarder in eg. `/var/lib/logstash-forwarder` and write the state file there.

```
# ls -lah /.logstash-forwarder
-rw-r--r-- 1 root root 1.6K Feb 27 10:51 /.logstash-forwarder
```

ps.: thx for your awesome program, please do not think wrong about my few reported bugs, it's because i like the program! And also want to help fixing them, it's just that the http://www.elasticsearch.org/contributor-agreement doesn't work here, i've to look at it later.

**Comment by jordansissel** [comment]
@gebi logstash-forwarder writes to $PWD/.logstash-forwarder. Please `cd /some/path` to write to this location.

We may add a flag eventually, but this is good enough for now.

**Comment by gebi** [comment]
Sorry, i'm using the provided init script to start logstash-forwarder and it writes to / in the default config which is not acceptable.

(please reopen this issue!)
