### ISSUE TITLE
Clarify where bugs should be reported

### ISSUE THREAD

**Issue by gebi** [elasticsearch/logstash-forwarder#398]
Hi,

The "guidlines for contributing" https://github.com/elasticsearch/logstash-forwarder/blob/master/CONTRIBUTING.md states bugs should be reported in `jira`, but every jira link in the documentation goes to https://github.com/jordansissel/lumberjack.

I found https://logstash.jira.com/, should bugs regarding logstash-forwarder be reported there?

**Comment by jordansissel** [comment]
3f494c0 should help resolve this.

**Comment by gebi** [comment]
thx :)!
