### ISSUE TITLE
Document Certificate Validation Problem with IP in DN instead of Hostname

### ISSUE THREAD

**Issue by gebi** [elasticsearch/logstash-forwarder#400]
Hi,

As most users are not yet familiar with the picky go implementation about IP in DN please document it in https://github.com/elasticsearch/logstash-forwarder/blob/master/README.md#generating-an-ssl-certificate

Something like:
Go (correctly) does not accept IPs in the DN of a certificate as most other implementations do, thus if you see some error message of logstash-forwarder like:
```
x509: cannot validate certificate for YOUR-IP because it doesn't contain any IP SANs
```
Please use the hostname of your machine to connect (where the hostname needs to be the `DN` in the certificate) or include IP SANs in your certificate.

Would save you a lot of support trouble ;)

**Comment by jordansissel** [comment]
@gebi I've tried this explanation, but I get gripes from (many!) people who do not even have DNS at all in their infrastructure and insist they require IP SANs.

I've given up. Nobody knows how to generate SSL certificates.

I'll update teh readme to include `-subj /CN=some.host.name` to help folks along who do have DNS, but ultimately self-signed certs probably aren't a great "for production" thing either.

**Comment by jordansissel** [comment]
Oh, I forgot, this was already done. 

```
openssl req -x509  -batch -nodes -newkey rsa:2048 -keyout lumberjack.key -out lumberjack.crt -subj /CN=logstash.example.com
```

Is what the readme says right now. Was changed in 0e22bad9

**Comment by jordansissel** [comment]
Unless I've misunderstood what you're saying, I think this information is already in the README.

**Comment by jordansissel** [comment]
#402 should include something I hope solves this.

**Comment by gebi** [comment]
For people without DNS in their infrastructure and without knowledge of `/etc/hosts` there is no hope ;). Maybe mention `/etc/hosts` in the documentation as a fix for infrastructures without DNS?
