### ISSUE TITLE
Regression in build

### ISSUE THREAD

**Issue by ofir-rounds** [elasticsearch/logstash-forwarder#405]
Found the issue, you added a switch to "pleaserun" called "sysv-log-path"
That was tagged under v0.0.11.
While you did gem update it didn't exists yet? resulting in Gemfile.lock using v0.0.10.

So commit 94eb0058dabc9f2ae125fecaac52bf2c49f25985 isn't what you wanted and so commit b83527073fba58b16a1a26a6aab4c918f2e15519 broke the build...

**Comment by ofir-rounds** [comment]
I think it's something on my side

**Comment by ofir-rounds** [comment]
https://github.com/elasticsearch/logstash-forwarder/pull/406

**Comment by jordansissel** [comment]
Fixed by #411

**Comment by jordansissel** [comment]
Thank you for reporting this :)
