### ISSUE TITLE
Whole output goes to logstash-forwarder.err

### ISSUE THREAD

**Issue by checkmypi** [elasticsearch/logstash-forwarder#408]
Logstash-forwarder init script splits stdout and stderr to different files.
But in reality whole output from logstash-forwarder seem to go stderr 
so all messages end up in logstash-forwarder.err

I'd recommend actually splitting valuable information from errors and logging them correctly

**Comment by jordansissel** [comment]
Use -quiet if you don't want informational messages. Otherwise, there is no way to split the log messages within logstash-forwarder as a user.

**Comment by checkmypi** [comment]
My logstash-forwarder.log was always empty.
Wouldn't it be better then to log into .log file ( 2>&1  ) in the init 
instead of 2>>logstash-forwarder.err ?

**Comment by jordansissel** [comment]
It's OK to be empty.

The init script is generated by another project. It is not hand-crafted. An empty .out file is normal.

**Comment by jordansissel** [comment]
If you wish an alternative, you can set the `-syslog` flag on logstash-forwarder and make it write logs to your local syslog system instead. You'll need to reconfigure the init script to do this.

**Comment by jordansissel** [comment]
Tracking this in #395 (closing this as a duplicate)
