### ISSUE TITLE
Support watching transient files

### ISSUE THREAD

**Issue by jvoorhis** [elasticsearch/logstash-forwarder#41]
Currently when a file specified on the command line does not exist, lumberjack dies with an assertion. It's also impossible to detect new files as they appear. Lumberjack would be even more useful if it could monitor transient logfiles matching a pattern specified on the command line. Example

    $ /opt/lumberjack/bin/lumberjack --host 127.0.0.1 \
       --port 1234 \
       --ssl-ca-path /path/to/cert \
        /path/to/logs/job-\*.log

**Comment by jordansissel** [comment]
I think this is resolved in newer editions of lsf which watch paths more liberally. Please reopen if this is not the case.
