### ISSUE TITLE
Harvester stops forwarding logs

### ISSUE THREAD

**Issue by knalli** [elasticsearch/logstash-forwarder#410]
I'm currently fighting with an issue in which logstash-forwarder stops forwarding the logs.

Both setups of mine (one in-building local and another one at AWS) stop unpredictable to send logs. The situation is both more less equal: _n hosts_ running logstash-forwarder collecting a set of logfiles and shipping them to one central host (serving the ELK stack with Logstash 1.5 Beta :warning:  ).

All works fine for hours and suddenly the logstash-forwarder stops...

_(log has been removed, invalid)_

There is no other warning, error or log. Also logstash does not report anything. And I can confirm that logstash itself is still able to consume data (lumberjack). The forwarder-process does not look to be stucked or defuncted:

```
%CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
0.0  0.3 219628  7052 ?        Sl   16:50   0:06 /opt/logstash-forwarder/bin/logstash-forwarder -config /etc/logstash-forwarder -spool-size 100
```

Additionally, I've even tried to use a more fresh binary and compiled it with 86889b6 (current master). No changes for me... :(

I would like to debug this, however I have no plan getting more information about the underlaying problem or the current state.. Does there exist more debugging, logging?

**Comment by jordansissel** [comment]
> All works fine for hours and suddenly the logstash-forwarder stops...

I am not sure I understand. 8 seconds before your 'date' command was LSF saying it had processed 4 events.

How are you observing the "suddenly stops" ?

**Comment by knalli** [comment]
@jordansissel .. aahh.. you are to fast. I've noticed I've copied wrong logs..

**Comment by jordansissel** [comment]
hehe, happy to help out. Let me know if you are still having trouble and what you're observing. :)

**Comment by knalli** [comment]
Sigh..  that is kind of embarrassing. Atm it is working.. I'll close this again, we will see tomorrow.

Anyway.. thank you for the very fast response.

Does already exist a next-release-date? I mean, the next after 0.3.1?

**Comment by jordansissel** [comment]
I'm hoping to have the release out today or tomorrow.
