### ISSUE TITLE
make rpm error

### ISSUE THREAD

**Issue by evalencia** [elasticsearch/logstash-forwarder#413]
Hi all,

Im running "make rpm" on ubuntu and getting the following error: 

ERROR: Unrecognised option '--sysv-log-path'

If I update Makefile by removing the following line I cann create the rpm when I run make again.

                --sysv-log-path /var/log/logstash-forwarder/ \

Is creating the rpm dependent on having a rhel based system?

**Comment by jordansissel** [comment]
I swear I fixed this. Blah! Sorry about this.

**Comment by jordansissel** [comment]
#411 should have fixed this. Can you run `bundle install` and try `make rpm` again?

**Comment by evalencia** [comment]
Looks good, error is gone.
Created package {:path=>"logstash-forwarder-0.4.0-1.x86_64.rpm"}

**Comment by jordansissel** [comment]
*whew*

Glad it's working!

**Comment by jordansissel** [comment]
Let me know if you have any other troubles :)
