### ISSUE TITLE
lumberjack output log file with nohup

### ISSUE THREAD

**Issue by douglasdedo** [elasticsearch/logstash-forwarder#58]
I tried to execute the lumberjack.sh with nohup but there is no log on nohup.out:

$ nohup /opt/lumberjack/bin/lumberjack --ssl-ca-path /etc/ssl/logstash.pub --host 10.196.51.168 --port 5000 /var/log/messages&
$ ll nohup
-rw------- 1 root root 0 Jul 12 18:19 nohup.out

When I execute without nohup, I can see the lumberjack log on console, like this:

$ /opt/lumberjack/bin/lumberjack --ssl-ca-path /etc/ssl/logstash.pub --host 10.196.51.168 --port 5000 /var/log/messages
2013-07-12T18:22:28.336+0000 Watching 1 files, setting open file limit to 103
2013-07-12T18:22:28.337+0000 Watching 1 files, setting memory usage limit to 1048576 bytes
2013-07-12T18:24:48.617+0000 Connecting to 10.196.51.168(10.196.51.168):5000

Any idea?

**Comment by jordansissel** [comment]
This bug was for the C version of lumberjack, lsf is now in Go; I'm not sure it's affected anymore.
