### ISSUE TITLE
Lumberjack only follows the first of multiple files listed

### ISSUE THREAD

**Issue by boinger** [elasticsearch/logstash-forwarder#60]
Using this in my run script:
  exec /opt/lumberjack/bin/lumberjack.sh --host logstash.internal --port 5005 --ssl-ca-path /etc/lumberjack/syslog/ca.crt --field type=syslog /var/log/secure /var/log/messages /var/log/*.log

I only see /var/log/secure streaming into logstash

Fixed by doing this (ghetto):
  exec tail -F /var/log/secure /var/log/messages /var/log/*.log | /opt/lumberjack/bin/lumberjack.sh --host logstash.internal --port 5005 --ssl-ca-path /etc/lumberjack/syslog/ca.crt --field type=syslog -

**Comment by jordansissel** [comment]
I think this bug was for the C version of lumberjack, lsf is now in Go; I'm not sure it's affected anymore. Please reopen if you're still hitting this in the newer logstash-forwarder.
