### ISSUE TITLE
Init script not working with Fedora 17

### ISSUE THREAD

**Issue by dusty** [elasticsearch/logstash-forwarder#75]
The init script is referencing non-existing files on Fedora 17.

Running it shows:
/etc/init.d/lumberjack: line 27: /lib/init/vars.sh: No such file or directory

It also references /lib/lsb/init-functions, which doesn't exist.

We are starting via monit and our own init scripts, so its not much of an issue.  I usually do that anyway.  But, the documentation does refer people to create the RPM, so it could cause frustration for some.  

Perhaps some documentation on systems the init script is known to work on would be helpful and a disclaimer to change it on your own if you run something else.  Not sure if you want to have to support init scripts for every os out there.  

I was thinking maybe this needs to go in FPM, but It looks like its referencing lumberjack.init in the Makefile.

**Comment by jordansissel** [comment]
We use pleaserun to generate the init script now, which should work on most linux platforms.

**Comment by jordansissel** [comment]
the new init script is built with master and will be a part of the next release.

**Comment by jordansissel** [comment]
This is fixed in #402
