### ISSUE TITLE
new files via wildcard; missing events

### ISSUE THREAD

**Issue by mattjbarker** [elasticsearch/logstash-forwarder#83]
I recently built lumberjack in the past day or two and encountered a problem.

I have it seeking for files in /var/log/apache2/some_rotated_log*

When apache rotates to a new log index, lumberjack takes a few seconds to pickup the new file and doesn't seek from the beginning. This appears to cause missed events while it tails the new log.

You can reproduce this issue by setting lumberjack to parse for a wildcard and echo "some line" > watched_file, wait 20 seconds, then echo another line. It'll send the second, but not the first. It would be awesome to implement a flag to have the harvester seek from the beginning of a new file.

**Comment by jordansissel** [comment]
This is fixed in master. Will appera in 0.4.0
