### ISSUE TITLE
lumberjack sees logfiles but never connects to server

### ISSUE THREAD

**Issue by jsmith1201** [elasticsearch/logstash-forwarder#90]
Hello,

Love lumberjack and logstash but suddenly having problems, lumberjack on two new servers (all RHEL 6) fails to connect, never gives the Connecting to or Connected Successfully message, this is a production logstash server other clients are sending to. 
I tried to install the latest lumberjack but the new version requires go which seems to have no RHEL/Centos support.  Tried to add error logging in the lumberjack_tcp_connect function in proto.c in the old c version but it won't build after a make clean, gives a message  error: jemalloc/jemalloc.h: No such file or directory even though I can see the jemalloc.h file in the directory cc calls out in the -Ibuild/include command line switch.
Any suggestions on how to debug the connection problem or how to proceed to use lumberjack on RHEL/Centos 6?
Thanks again!

**Comment by jordansissel** [comment]
I think this bug was for the C version of lumberjack, lsf is now in Go; I'm not sure it's affected anymore. Please reopen if you're still hitting this in the newer logstash-forwarder.
