### ISSUE TITLE
Default path for the creation of the .lumberjack.new and .lumberjack

### ISSUE THREAD

**Issue by sbarrier** [elasticsearch/logstash-forwarder#94]
Failed to open .lumberjack.new for writing: open .lumberjack.new: permission denied

Lumberjack try to create this file in the directory it's started but if this directory is not owned by lumberjack user it fail. It would be great to be able to configure the directory and to default to /tmp if it's not configured

**Comment by jordansissel** [comment]
For now, please `cd` to the place you want lsf to operate. There's a few PRs to add a setting to control the location, but again, for now, use `cd`. The init script in master does this, for example.
